version: 2
jobs:
  build:
    working_directory: ~/project
    docker:
      - image: circleci/android:api-27-alpha
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "sample/build.gradle" }}
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - run:
          name: Assemble
          command: ./gradlew assemble -PdisablePreDex
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "sample/build.gradle" }}
      - store_artifacts:
          path: sample/build/outputs/apk
  test:
    working_directory: ~/project
    docker:
      - image: circleci/android:api-27-alpha
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "sample/build.gradle" }}
      - run:
          name: Run tests
          command: ./gradlew test -PdisablePreDex
      - store_artifacts:
          path: sample/build/reports
          destination: reports
      - store_test_results:
          path: sample/build/test-results
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "sample/build.gradle" }}
  test_api_v19:
      working_directory: ~/project
      docker:
        - image: circleci/android:api-27-alpha
      environment:
        JVM_OPTS: -Xmx3200m
      steps:
        - checkout
        - run:
            name: Setup emulator
            command: sdkmanager "system-images;android-19;default;armeabi-v7a" && echo "no" | avdmanager create avd -n test -k "system-images;android-19;default;armeabi-v7a"
        - run:
            name: Launch emulator
            command: export LD_LIBRARY_PATH=${ANDROID_HOME}/emulator/lib64:${ANDROID_HOME}/emulator/lib64/qt/lib && emulator64-arm -avd test -noaudio -no-boot-anim -no-window -accel on
            background: true
        - run:
            name: Wait emulator
            command: |
              # wait for it to have booted
              circle-android wait-for-boot
              # unlock the emulator screen
              sleep 30
              adb shell input keyevent 82
        - run:
            name: Run Tests
            command: ./gradlew connectedAndroidTest
        - store_artifacts:
            path: sample/build/reports
            destination: reports
        - store_test_results:
            path: sample/build/test-results

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
      - test_api_v19:
          requires:
            - build